---
title: "Hall-Yarborough"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hall-Yarborough}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Get `z` at selected `Ppr` and `Tpr`

```{r}
library(zFactor)

z.HallYarborough(pres.pr = 1.5, temp.pr = 2.0)
```

From the Standing-Katz chart we obtain a digitized point:

```{r}
library(zFactor)

tpr_vec <- c(2.0)
getStandingKatzMatrix(tpr_vector = tpr_vec, 
                      pprRange = "lp")[1, "1.5"]
```



## Get `z` at selected `Ppr` and `Tpr`

```{r}
library(zFactor)

z.HallYarborough(pres.pr = 1.5, temp.pr = 1.1)
```

From the Standing-Katz chart we obtain a digitized point:

```{r}
library(zFactor)

tpr_vec <- c(1.1)
getStandingKatzMatrix(tpr_vector = tpr_vec, 
                      pprRange = "lp")[1, "1.5"]
```

> We perceve noticeable difference between the values of z from the HY calculation and the value read from the Standing-Katz chart.


## Get values of `z` for several `Ppr` and `Tpr`

```{r}
# test HY with 1st-derivative using the values from paper 
 
ppr <- c(0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5) 
tpr <- c(1.3, 1.5, 1.7, 2) 
 
tbl <- sapply(ppr, function(x)  
    sapply(tpr, function(y) z.HallYarborough(pres.pr = x, temp.pr = y))) 
 
rownames(tbl) <- tpr 
colnames(tbl) <- ppr 
print(tbl) 
```

