---
title: "Plot Standing-Katz low-pressure charts"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(zFactor)

getStandingKatzCurve(tpr = 1.05, toSave = FALSE, toView = FALSE)
```

```{r}
# view all the `Tpr` SK individual charts
tpr_vec <- getCurvesDigitized(pprRange = "lp")

invisible(sapply(tpr_vec, function(x) getStandingKatzCurve(tpr = x, 
                                                           toSave = FALSE, 
                                                           toView = FALSE)))
```


## All in one chart

These two functions are equivalent:

```{r}
library(zFactor)

tpr_vec <- c(1.05, 1.3, 1.5)

all_tpr1 <- (lapply(tpr_vec, function(x) getStandingKatzCurve(tpr = x, 
                                                           toSave = FALSE, 
                                                           toView = FALSE,
                                                           toPlot = FALSE)))

```


```{r}
library(zFactor)

tpr_vec <- c(1.05, 1.3, 1.5)
all_tpr2 <- (lapply(tpr_vec, function(x) getStandingKatzData(tpr = x)))
names(all_tpr2) <- tpr_vec
```


Now, we have to create a tidy datatset from the list.


```{r}
library(data.table)

all_tpr_df <- data.table::rbindlist(all_tpr2, idcol = TRUE)
colnames(all_tpr_df)[1] <- "Tpr"
```


Let's plot the curves:

```{r}
library(ggplot2)

ggplot(all_tpr_df, aes(x=Ppr, y=z, group=Tpr, color=Tpr)) + 
    geom_line() +
    geom_point()
```

