---
title: "R Notebook"
output: html_notebook
---


```{r}
library(zFactor)
sum_tpr <- as.tibble(z.stats("HY"))
sum_tpr$Tpr <- as.numeric(sum_tpr$Tpr)
sum_tpr$Ppr <- as.numeric(sum_tpr$Ppr)

library(rsm)

swiss2.lm <- lm(RMSE ~ poly(Ppr, Tpr, degree=2), data=sum_tpr)
par(mfrow=c(1,3))
image(swiss2.lm, Tpr ~ Ppr)
contour(swiss2.lm, Tpr ~ Ppr)
# persp(swiss2.lm, Tpr ~ Ppr, zlab = "RMSE")
```




```{r}
# Ppr  <- as.numeric(sum_tpr$Ppr)
# Tpr  <- as.numeric(sum_tpr$Tpr)
# RMSE <- sum_tpr$RMSE

sum_tpr <- as.tibble(z.stats("N10"))

sum_tpr$Tpr <- as.numeric(sum_tpr$Tpr)
sum_tpr$Ppr <- as.numeric(sum_tpr$Ppr)


data.loess <- loess(RMSE ~ Ppr * Tpr, data = sum_tpr)

xgrid <- seq(min(sum_tpr$Ppr), max(sum_tpr$Ppr), 0.1)
ygrid <- seq(min(sum_tpr$Tpr), max(sum_tpr$Tpr), 0.2)

data.fit <- expand.grid(Ppr = xgrid, Tpr = ygrid)
mtrx3d <-  predict(data.loess, newdata = data.fit)

contour(x = xgrid, y = ygrid, z = mtrx3d, nlev = 10, method = "edge")
```

```{r}
contour(x = xgrid, y = ygrid, z = mtrx3d)
```