---
title: "R Notebook"
output: html_notebook
---

```{r}
system("java -version")
system("javac -version")
```

```{r}
# compile Java code
system("javac -verbose ./java/CalculateZFactor.java")
```

```{r}
# preliminaries #
library(rJava)

# start the Java Virtual Machine
.jinit()

# replace with the path to the folder containing your class
.jaddClassPath("./java")     

# show the Java class path
.jclassPath()
```

```{r}
zFactor <- .jnew("CalculateZFactor")
```

```{r}
.jcall(zFactor, "D", "ANN10", 0.5, 1.3)
```

```{r}
.jcall(zFactor, "D", "ANN10", 0.5, 1.3)
```

```{r}
.jcall(zFactor, "D", "ANN5", 0.5, 1.5)
```

```{r}
.jcall(zFactor, "D", "ANN10", 0.5, 1.05)
.jcall(zFactor, "D", "ANN10", 0.5, 1.10)

.jcall(zFactor, "D", "ANN10", 5.5, 1.05)
.jcall(zFactor, "D", "ANN10", 5.5, 1.10)
```



```{r}
ppr <- c(0.5, 1.5, 2.5, 3.5, 4.5, 5.5)
tpr <- c(1.05, 1.1)

mx <- sapply(ppr, function(x) sapply(tpr, function(y)
    .jcall(zFactor, "D", "ANN10", x, y)) 
)

colnames(mx) <- ppr
rownames(mx) <- tpr
mx
```


```{r}
ann10 <- function(ppr, tpr) {
    mx <- sapply(ppr, function(x) sapply(tpr, function(y)
    .jcall(zFactor, "D", "ANN10", x, y)) )
    mx
}

ann10(ppr, tpr)
```

```{r}
ann5 <- function(ppr, tpr) {
    mx <- sapply(ppr, function(x) sapply(tpr, function(y)
    .jcall(zFactor, "D", "ANN5", x, y)) )
    mx
}

ann5(ppr, tpr)
```



```{r}
library(rJava)

Ann10 <- function(ppt, tpr) {
    zFactor <- .jnew("CalculateZFactor")
    z <- .jcall(zFactor, "D", "ANN10", ppr, tpr)    
    z
}


Ann10(0.5, 1.05)
```






```{r}
# call the my_convolve.class
z = .jcall("CalculateZFactor", "D", "ANN10", 
           as.double(1.0), as.double(1.05))
z
```


```{r}
# call the my_convolve.class
z = .jcall("CalculateZFactor", "D", "ANN10", 
           1.2, 1.05)
z
```

```{r}
# call the my_convolve.class
z = .jcall("CalculateZFactor", "D", "DAK", 
           as.double(1.0), as.double(1.05))
z
```






